title: ollyj.uk
author: Olly Wiggins
email: olly@ollyj.uk
description: Thoughts & Pears

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    linkedin: http://linkedin.com/in/olly/
    spotify: https://open.spotify.com/user/11173788945/playlist/1txSunJXQwNszOElPKUKz6?si=43kMdLSPTOKL9l8vkGXdTw
    nexus: https://www.instagram.com/nexusmusicuk/
    metblue: https://www.instagram.com/metropolis.blue/ 

# Hide certain pages by excluding them from the list
header_pages:
 - about.md
 - portfolio.md
 - archive.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
