title: hey. i'm olly.
url: https://ojw.me

# generate social links in footer
social:
  linkedin: https://linkedin.com/in/olly/
  github: https://github.com/ollyyj/ollyyj.github.io
  project: https://www.instagram.com/p/B3rGCi-BLhE/

plugins:
 - jekyll-seo-tag
