title: Olly Wiggins
author: Olly Wiggins
email: olly@ollyj.uk
dbs: July 2019

# generate social links in footer
social:
  linkedin: http://linkedin.com/in/olly/
  lastfm: https://www.last.fm/user/ollyyj

minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-stickyposts
