title: Olly Wiggins
author: Olly Wiggins
email: olly@ollyj.uk
dbs: July 2019

# generate social links in footer
social:
  linkedin: https://linkedin.com/in/olly/
  lastfm: https://last.fm/user/ollyyj
  twitter: https://twitter.com/ollyj_

minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-stickyposts
