plugins:
  - jekyll-sitemap

title: Olly Wiggins
tagline: The portfolio site of Olly Wiggins.
description:
url: ojw.me
author: Olly Wiggins

twitter:
  username: ollywiggins_
  card: summary

excerpt_separator: <!--more-->

social:
  linkedin: https://linkedin.com/in/olly/
  twitter: https://twitter.com/ollywiggins_
  youtube: https://www.youtube.com/channel/UCp7oMylSKVYKUiPRxqE6E8A
  email: olly@ojw.me
