title: ollyj.uk
author: Olly Wiggins
email: olly@ollyj.uk
description: Thoughts & Pears

show_excerpts: false # set to true to show excerpts on the homepage

# generate social links in footer
social:
  linkedin: http://linkedin.com/in/olly/
  spotify: spotify:user:11173788945:playlist:1txSunJXQwNszOElPKUKz6
  metblue: https://www.facebook.com/metropolisblue
  github: https://github.com/ollyyj/ollyyj.github.io
  lastfm: https://www.last.fm/user/ollyyj

minima:
  date_format: "%b %-d, %Y"


# Hide certain pages by excluding them from the list
header_pages:
 - blog.md
 - portfolio.md
 - playlists.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 #- jekyll-stickyposts
